# Generated by Django 5.0.4 on 2024-05-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.FileField(max_length=500, upload_to='photo_for_users'),
        ),
    ]
