# Generated by Django 5.0.4 on 2024-04-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_photo', '0002_rename_image_picture_file_picture_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
