# Generated by Django 5.0.4 on 2024-04-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_photo', '0004_remove_picture_file_remove_picture_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.FileField(upload_to='photo_for_users'),
        ),
    ]
